apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-manager
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://charts.jetstack.io
    chart: cert-manager
    targetRevision: v1.17.1
    helm:
      parameters:
        - name: crds.enabled
          value: "true"
        - name: global.resources.requests.cpu
          value: "10m"  
        - name: global.resources.requests.memory
          value: "20Mi"  
        - name: global.resources.limits.cpu
          value: "50m"  
        - name: global.resources.limits.memory
          value: "100Mi"  
        - name: cainjector.resources.requests.cpu
          value: "5m"
        - name: cainjector.resources.requests.memory
          value: "20Mi"
        - name: cainjector.resources.limits.cpu
          value: "10m"
        - name: cainjector.resources.limits.memory
          value: "50Mi"
        - name: webhook.resources.requests.cpu
          value: "5m"
        - name: webhook.resources.requests.memory
          value: "20Mi"
        - name: webhook.resources.limits.cpu
          value: "10m"
        - name: webhook.resources.limits.memory
          value: "50Mi"
        - name: startupapicheck.resources.requests.cpu
          value: "5m"
        - name: startupapicheck.resources.requests.memory
          value: "20Mi"
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
