apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator2-sa
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: operator2-clusterrole
rules:
  - apiGroups: ["jones.com"]
    resources:
      - contexts
      - servicealts
      - domaintopics
      - applicationtopics
    verbs: ["get", "list", "watch"]

  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: operator2-clusterrolebinding
subjects:
  - kind: ServiceAccount
    name: operator2-sa
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: operator2-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: operator2-deployment
  namespace: argocd
  labels:
    app: operator2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: operator2
  template:
    metadata:
      labels:
        app: operator2
    spec:
      serviceAccountName: operator2-sa
      containers:
        - name: operator
          image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi