apiVersion: v1
kind: ServiceAccount
metadata:
  name: kafka-topic-operator-sa
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-topic-operator-clusterrole
rules:
  - apiGroups: ["jones.com"]
    resources: ["applicationtopics"]
    verbs: ["get", "list", "watch", "patch", "update"]
  - apiGroups: ["jones.com"]
    resources: ["applicationtopics/status"]
    verbs: ["get", "patch", "update"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-topic-operator-clusterbinding
subjects:
  - kind: ServiceAccount
    name: kafka-topic-operator-sa
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: kafka-topic-operator-clusterrole
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-operator
  namespace: argocd
  labels:
    app: kafka-topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-operator
  template:
    metadata:
      labels:
        app: kafka-topic-operator
    spec:
      serviceAccountName: kafka-topic-operator-sa
      containers:
        - name: operator
          image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest
          env:
            - name: CONFLUENT_BOOTSTRAP_SERVERS
              value: "pkc-z1o60.europe-west1.gcp.confluent.cloud:9092"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi