apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-operator
  namespace: argocd
  labels:
    app: kafka-topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-operator
  template:
    metadata:
      labels:
        app: kafka-topic-operator
    spec:
      serviceAccountName: kafka-topic-operator-sa
      containers:
        - name: operator
          image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest
          env:
            - name: CONFLUENT_BOOTSTRAP_SERVERS
              value: "http://pkc-z1o60.europe-west1.gcp.confluent.cloud:9092"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: argocd
  name: kafka-topic-operator-role
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-topic-operator-rolebinding
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: kafka-topic-operator-sa
    namespace: argocd
roleRef:
  kind: Role
  name: kafka-topic-operator-role
  apiGroup: rbac.authorization.k8s.io
