apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-operator
  namespace: argocd
  labels:
    app: kafka-topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-operator
  template:
    metadata:
      labels:
        app: kafka-topic-operator
    spec:
      serviceAccountName: kopf-operator-sa # <-- changed here
      containers:
        - name: operator
          image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest
          env:
            - name: CONFLUENT_BOOTSTRAP_SERVERS
              value: "localhost:9092"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kopf-operator-sa # <-- changed here
  namespace: argocd

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kopf-operator-role # <-- renamed to match
  namespace: argocd
rules:
  - apiGroups: [""]
    resources: ["pods", "services"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kopf-operator-rolebinding # <-- renamed to match
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: kopf-operator-sa # <-- changed here
    namespace: argocd
roleRef:
  kind: Role
  name: kopf-operator-role # <-- changed here
  apiGroup: rbac.authorization.k8s.io

