apiVersion: apps/v1
kind: Deployment
metadata:
  name: application-operator
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: application-operator
  template:
    metadata:
      labels:
        app: application-operator
    spec:
      serviceAccountName: operator-ro
      containers:
        - name: application-operator
          image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest  # Replace with your operator's image
          imagePullPolicy: Always
          env:
            - name: KUBERNETES_SERVICE_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: KUBERNETES_SERVICE_PORT
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: operator-ro
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  rules:
    - apiGroups: ["jones.com"]
      resources: ["applicationtopics"]
      verbs: ["create", "list", "get", "watch"]
    - apiGroups: [""]
      resources: ["pods"]
      verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: operator-ro-binding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: operator-ro
    namespace: default
roleRef:
  kind: Role
  name: operator-ro
  apiGroup: rbac.authorization.k8s.io
