apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: operator
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bryancymo/cymo-hogent-2025-operator.git
    targetRevision: HEAD
    path: operator
  destination:
    server: https://kubernetes.default.svc
    namespace: operator # or another namespace if needed
  syncPolicy:
    automated:
      selfHeal: true
      prune: true

