apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: contexts.jones.com
  annotations:
    description: "CRD voor Contexts"
spec:
  group: jones.com
  names:
    kind: Context
    plural: contexts
    singular: context
    shortNames:
      - ctx
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - owner
                - developerGroups
              properties:
                name:
                  type: string
                owner:
                  type: string
                developerGroups:
                  type: array
                  items:
                    type: string
--- 

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: services.jones.com
  annotations:
    description: "CRD voor Services"
spec:
  group: jones.com
  names:
    kind: Service
    plural: services
    singular: service
    shortNames:
      - csvc
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - contextLink
                - secretSolution
              properties:
                name:
                  type: string
                contextLink:
                  type: string
                  description: "Link naar een Context resource"
                secretSolution:
                  type: string
                  description: "Naam secret"