apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: contexts.jones.com
  annotations:
    description: "CRD voor Contexts"
spec:
  group: jones.com
  names:
    kind: Context
    plural: contexts
    singular: context
    shortNames:
      - ctx
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              required:
                - name
                - owner
                - developerGroups
              properties:
                name:
                  type: string
                owner:
                  type: string
                developerGroups:
                  type: array
                  items:
                    type: string
--- 

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: cservices.jones.com
  annotations:
    description: "CRD voor Services"
spec:
  group: jones.com
  names:
    kind: Cservice
    plural: cservices
    singular: cservice
    shortNames:
      - csvc
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          required: ["spec"]  # ✅ Ensures `spec` is always present
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:  # ✅ FIX: Only allow `name` and `generateName`
              type: object
              properties:
                name:
                  type: string
                generateName:
                  type: string
            spec:
              type: object
              required:
                - name
                - contextLink
                - secretSolution
              properties:
                name:
                  type: string
                contextLink:
                  type: string
                  description: "Link naar een Context resource"
                secretSolution:
                  type: string
                  description: "Naam secret"

--- 

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: domaintopics.jones.com
  annotations:
    description: "CRD voor domain topics in Kubernetes"
spec:
  group: jones.com
  names:
    kind: Domaintopic
    plural: domaintopics
    singular: domaintopic
    shortNames:
      - dt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                config:
                  type: object
                  properties:
                    retentionMs:
                      type: integer
                    replicationFactor:
                      type: integer
                    cleanupPolicy:
                      type: string
                consumers:
                  type: array
                  items:
                    type: string
                partitions:
                  type: integer
---

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: applicationtopics.jones.com
  annotations:
    description: "crd voor applicatie topics in Kubernetes"
spec:
  group: jones.com
  names:
    kind: ApplicationTopic
    plural: applicationtopics
    singular: applicationtopic
    shortNames:
      - apt
  scope: Namespaced
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              type: object
              properties:
                name:
                  type: string
                config:
                  type: object
                  properties:
                    retentionMs:
                      type: integer
                    replicationFactor:
                      type: integer
                    cleanupPolicy:
                      type: string
                consumers:
                  type: array
                  items:
                    type: string
                partitions:
                  type: integer