apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-operator
  namespace: argocd
  labels:
    app: kafka-topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-operator
  template:
    metadata:
      labels:
        app: kafka-topic-operator
    spec:
      serviceAccountName: intern-gke-cluster # Ensure this matches the service account
      containers:
      - name: operator
        image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest
        imagePullPolicy: Always
        env:
        - name: CONFLUENT_BOOTSTRAP_SERVERS
          value: "pkc-z1o60.europe-west1.gcp.confluent.cloud:9092"
        resources:
          requests:
            cpu: 10m
            memory: 128Mi
          limits:
            cpu: 200m
            memory: 256Mi
