apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-topic-operator
  namespace: argocd
  labels:
    app: kafka-topic-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-topic-operator
  template:
    metadata:
      labels:
        app: kafka-topic-operator
    spec:
      serviceAccountName: intern-gke-cluster  # Changed to 'intern-gke-cluster'
      containers:
        - name: operator
          image: eu.gcr.io/cymo-hogent-2025-operator/kopf-operator:latest
          imagePullPolicy: Always
          env:
            - name: CONFLUENT_BOOTSTRAP_SERVERS
              value: "pkc-z1o60.europe-west1.gcp.confluent.cloud:9092"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi

# IMPORTANT: This Deployment now uses the 'intern-gke-cluster' Kubernetes service account
# that needs to be correctly mapped to the Google Cloud service account 
# 'intern-gke-cluster@cymo-hogent-2025-operator.iam.gserviceaccount.com'.