apiVersion: jones.com/v1
kind: DomainTopic
metadata:
  name: test-domaintopic08056
  namespace: argocd
spec:
  name: test-domaintopic08056
  partitions: 1
  config:
    retentionMs: 604800000  # 7 days in milliseconds
    cleanupPolicy: "delete"
    replicationFactor: 3
  consumers: [] 