apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt08056
  namespace: argocd
spec:
  name: test-servicealt08056
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: ApplicationTopic
metadata:
  name: test-applicationtopic08056
  namespace: argocd
spec:
  name: test-applicationtopic08056
  partitions: 3
  config:
    retentionMs: 604800000  # 7 days in milliseconds
    cleanupPolicy: "delete"
    replicationFactor: 3
  consumers: []