apiVersion: jones.com/v1
kind: Context
metadata:
  name: test-context
  namespace: argocd
spec:
  name: test-context
  owner: your-owner
  developerGroups:
    - dev-group1
    - dev-group2
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt
  namespace: argocd
spec:
  name: test-servicealt
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: ApplicationTopic
metadata:
  name: test-topic
  namespace: argocd
spec:
  name: my-app-topic
  partitions: 3
  config:
    retentionMs: 3600000
    replicationFactor: 2
    cleanupPolicy: delete
  consumers:
    - service1
    - service2
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: example-servicealt
spec:
  name: myservice
  contextLink: context-link
  secretSolution: supersecret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: my-new-servicealt
  namespace: argocd
spec:
  name: testingservice
  contextLink: context-link
  secretSolution: supersecret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: hogent-test1019
  namespace: argocd
spec:
  name: hogent-test1019
  contextLink: context-link
  secretSolution: supersecret
---
apiVersion: jones.com/v1
kind: ApplicationTopic
metadata:
  name: test-topic2
  namespace: argocd
spec:
  name: test-topic2
  partitions: 3
  config:
    retentionMs: 3600000
    replicationFactor: 2
    cleanupPolicy: delete
  consumers:
    - service1
    - service2