apiVersion: jones.com/v1
kind: Context
metadata:
  name: test-context
  namespace: operator
spec:
  name: test-context
  owner: your-owner
  developerGroups:
    - dev-group1
    - dev-group2
---
apiVersion: jones.com/v1
kind: Cservice
metadata:
  name: test-cservice
  namespace: operator
spec:
  name: test-cservice
  contextLink: test-context
  secretSolution: test-secret
