apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt12
  namespace: argocd
spec:
  name: test-servicealt12
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: service2504
  namespace: argocd
spec:
  name: service2504
  contextLink: test-context
  secretSolution: test-secret