apiVersion: jones.com/v1
kind: Environment
metadata:
  name: test-environment
  namespace: operator
spec:
  context:
    name: test-context
    owner: your-owner
    developerGroups:
      - dev-group1
      - dev-group2
  services:
    - name: test-servicealt
      contextLink: test-context
      secretSolution: test-secret
    - name: example-servicealt
      contextLink: test-context
      secretSolution: supersecret
  applications:
    - name: test-topic
      namespace: argocd
      config:
        retentionMs: 3600000
        replicationFactor: 2
        cleanupPolicy: delete
      partitions: 3
      consumers:
        - service1
        - service2
