apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt1
  namespace: argocd
spec:
  name: test-servicealt1
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt2
  namespace: argocd
spec:
  name: test-servicealt2
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt3
  namespace: argocd
spec:
  name: test-servicealt3
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: ApplicationTopic
metadata:
  name: test-applicationtopic3
  namespace: argocd
spec:
  name: test-applicationtopic3
  partitions: 1
  config:
    retentionMs: 604800000  # 7 days in milliseconds
    cleanupPolicy: "delete"
    replicationFactor: 3
  consumers: []
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt4
  namespace: argocd
spec:
  name: test-servicealt4
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt4
  namespace: argocd
spec:
  name: test-servicealt4
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt5
  namespace: argocd
spec:
  name: test-servicealt5
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt6
  namespace: argocd 
spec:
  name: test-servicealt6
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt7
  namespace: argocd 
spec:
  name: test-servicealt7
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt8
  namespace: argocd 
spec:
  name: test-servicealt8
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt9
  namespace: argocd 
spec:
  name: test-servicealt9
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt10
  namespace: argocd 
spec:
  name: test-servicealt10
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt11
  namespace: argocd 
spec:
  name: test-servicealt11
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt12
  namespace: argocd 
spec:
  name: test-servicealt12
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt13
  namespace: argocd 
spec:
  name: test-servicealt13
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt14
  namespace: argocd 
spec:
  name: test-servicealt14
  contextLink: test-context
  secretSolution: test-secret

