apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt08057
  namespace: argocd
spec:
  name: test-servicealt08057
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt08056
  namespace: argocd
spec:
  name: test-servicealt08056
  contextLink: test-context
  secretSolution: test-secret