apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt1
  namespace: argocd
spec:
  name: test-servicealt1
  contextLink: test-context
  secretSolution: test-secret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: test-servicealt2
  namespace: argocd
spec:
  name: test-servicealt2
  contextLink: test-context
  secretSolution: test-secret

