apiVersion: jones.com/v1
kind: Context
metadata:
  name: test-context
  namespace: operator
spec:
  name: test-context
  owner: your-owner
  developerGroups:
    - dev-group1
    - dev-group2
---
apiVersion: jones.com/v1
kind: servicealt
metadata:
  name: retry-test
  namespace: argocd
spec:
  name: retry-test
  contextLink: dummy
  secretSolution: none
---
apiVersion: jones.com/v1
kind: ApplicationTopic
metadata:
  name: test-topic
  namespace: argocd
spec:
  name: my-app-topic
  partitions: 3
  config:
    retentionMs: 3600000
    replicationFactor: 2
    cleanupPolicy: delete
  consumers:
    - service1
    - service2
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: example-servicealt
spec:
  name: myservice
  contextLink: context-link
  secretSolution: supersecret
---
apiVersion: jones.com/v1
kind: Servicealt
metadata:
  name: my-new-servicealt
  namespace: argocd
spec:
  name: testingservice
  contextLink: context-link
  secretSolution: supersecret