apiVersion: jones.com/v1
kind: ApplicationTopic
metadata:
  name: test-applicationtopic08056
  namespace: argocd
spec:
  name: test-applicationtopic08056
  partitions: 1
  config:
    retentionMs: 604800000  # 7 days in milliseconds
    cleanupPolicy: "delete"
    replicationFactor: 3
  consumers: []
---
apiVersion: jones.com/v1
kind: Domaintopic
metadata:
  name: test-domaintopic08056
  namespace: argocd
spec:
  partitions: 1
  config:
    retentionMs: 604800000  # 7 days in milliseconds
    cleanupPolicy: "delete"
    replicationFactor: 3
  consumers: [] 
