apiVersion: v1
kind: ServiceAccount
metadata:
  name: intern-gke-cluster
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: kafka-topic-operator-role
  namespace: argocd
rules:
  - apiGroups: ["jones.com"]
    resources: ["applicationtopics"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: kafka-topic-operator-rb
  namespace: argocd
subjects:
  - kind: ServiceAccount
    name: intern-gke-cluster  # Changed to 'intern-gke-cluster'
    namespace: argocd
roleRef:
  kind: Role
  name: kafka-topic-operator-role
  apiGroup: rbac.authorization.k8s.io

# IMPORTANT: This RBAC configuration grants permissions *within* the Kubernetes cluster to the
# 'intern-gke-cluster' Kubernetes service account.
# It does NOT grant Google Cloud IAM permissions.
# The Google Cloud IAM permissions are handled separately and are needed to pull images from GCR/Artifact Registry.
# The google cloud service account 'intern-gke-cluster@cymo-hogent-2025-operator.iam.gserviceaccount.com' needs the correct permissions.
# Or, the kubernetes service account needs to be correctly mapped to that google cloud service account.