apiVersion: v1
kind: ServiceAccount
metadata:
  name: intern-gke-cluster
  namespace: argocd
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kafka-topic-operator-cluster-role
rules:
  # Allow access to all CRDs in the jones.com API group
  - apiGroups: ["jones.com"]
    resources: ["contexts", "servicealts", "domaintopics", "applicationtopics"]
    verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]

  # Allow access to custom resource definitions in the apiextensions.k8s.io API group
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch"]

  # Grant permissions for standard Kubernetes resources
  - apiGroups: [""]
    resources: ["pods", "services", "endpoints", "configmaps", "secrets"]
    verbs: ["get", "list", "watch"]

  # Allow Kopf to create events in any namespace
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["create"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kafka-topic-operator-cluster-rb
subjects:
  - kind: ServiceAccount
    name: intern-gke-cluster
    namespace: argocd
roleRef:
  kind: ClusterRole
  name: kafka-topic-operator-cluster-role
  apiGroup: rbac.authorization.k8s.io

# IMPORTANT: This RBAC configuration grants permissions *within* the Kubernetes cluster to the
# 'intern-gke-cluster' Kubernetes service account.
# It does NOT grant Google Cloud IAM permissions.
# The Google Cloud IAM permissions are handled separately and are needed to pull images from GCR/Artifact Registry.
# The google cloud service account 'intern-gke-cluster@cymo-hogent-2025-operator.iam.gserviceaccount.com' needs the correct permissions.
# Or, the kubernetes service account needs to be correctly mapped to that google cloud service account.
